### ISSUE TITLE
Closing the menu got some animation bug.

### ISSUE THREAD

**Issue by balram3429** [ITechRoof/ITRAirSideMenu#1]
Hi Kirthi,

Control looks good. But there are few bugs in closing of the menu.
1. The menu opens with a little pan towards right. Now if we release the Pan & try to close menu by dragging it towards left, its not getting closed.
2. While selecting any item from the side menu, the closing animation got a bug. Refer the screen shot.

Thanks,
Balram

![screen shot 2015-08-27 at 11 09 53 am](https://cloud.githubusercontent.com/assets/1736969/9513337/b981f292-4cac-11e5-9497-be2194068805.png)

**Comment by ITechRoof** [comment]
Fixed
