### ISSUE TITLE
A couple suggestions for improvement

### ISSUE THREAD

**Issue by andrebraga** [ITechRoof/ITRAirSideMenu#3]
Hi,

The leftMenuVisible property should be made public.
`@property (assign, readonly, nonatomic, getter=isLeftMenuVisible) BOOL leftMenuVisible;`

Also, as it stands, the pan recognizer is reacting to every scroll in every direction. It should only react to horizontal pans.

```
@implementation ITRAirSideMenu (OnlyReactToHorizontalPan)
- (BOOL)gestureRecognizerShouldBegin:(UIPanGestureRecognizer *)gestureRecognizer
{
    CGPoint translation = [gestureRecognizer translationInView:self.view];

    return fabs(translation.y) < fabs(translation.x);
}
@end
```

Thanks!

**Comment by andrebraga** [comment]
Submitted a couple PRs comprising this suggestion and a fix related to Xcode view debugging. :smiley:

**Comment by ITechRoof** [comment]
Reviewed your commit. Looks fine. Thanks for your contribution :)
